language: python
python:
  - "2.7"
  - "3.3"

# command to install dependencies
install: 
 - "python setup.py develop"
 - "pip install networkx"

# command to run tests
script: "cd tests && sh run_suite.sh"
